# Configuration for actions/labeler

"GUI/Qt":
  - any:
    - 'src/ui/**/*'

"Core":
  - any:
    - 'src/core/**/*'

"Build | Project System":
  - any:
    - 'CMakeLists.txt'
    - 'cmake/**/*'
    - '.github/**/*'
    - 'scripts/**/*'

"Linux":
  - any: ['**/*EGL*', '**/*linux*', '**/*Wayland*', '**/*X11*']

"Windows":
  - any: ['**/*WGL*', '**/*win32*', 'resources/myMCpp.rc']

"macOS":
  - any: ['src/core/renderer/Metal/**/*', '**/*AGL*', '**/*.mm', '**/*Cocoa*']

"CLI":
  - any:
    - 'src/cli/**/*'

"Vulkan":
  - any: ['**/vulkan*', '**/Vulkan*', 'src/core/renderer/Vulkan/**/*']

"OpenGL":
  - any: ['**/opengl*', '**/OpenGL*', 'src/core/renderer/OpenGL/**/*']

"Metal":
  - any: ['**/metal*', '**/Metal*', 'src/core/renderer/Metal/**/*']

"Documentation":
  - any:
    - 'docs/**/*'
    - 'README.md'
    - 'LICENSE.md'
    - 'build.md'
