<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutDir>$(SolutionDir)build\$(Platform)\$(Configuration)\</OutDir>
    <IntDir>$(SolutionDir)build\$(Platform)\$(Configuration)\obj\$(MSBuildProjectName)\</IntDir>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <ConformanceMode>true</ConformanceMode>
      <SDLCheck>true</SDLCheck>
      <WarningLevel>Level3</WarningLevel>
      <!-- TODO: Remove this when Qt 7 comes out-->
      <DisableSpecificWarnings>4996;%(DisableSpecificWarnings)</DisableSpecificWarnings>
      <AdditionalOptions>%(AdditionalOptions) /utf-8</AdditionalOptions>
      <PreprocessorDefinitions>ENABLE_VULKAN;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\..\3rdparty\3rdparty.props" />
</Project>
