# Inspired by PCSX2 CI Matrixes

name: 🔨 Build

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build_linux_x64_clang:
    name: "🐧 Linux x64 (Clang)"
    uses: ./.github/workflows/linux_build.yml
    with:
      jobName: "Linux x64 Clang Build"
      artifactPrefixName: "myMCpp-linux-x64-clang"
      platform: x64
      compiler: clang
    secrets: inherit

  build_linux_x64_gcc:
    name: "🐧 Linux x64 (GCC)"
    uses: ./.github/workflows/linux_build.yml
    with:
      jobName: "Linux x64 GCC Build"
      artifactPrefixName: "myMCpp-linux-x64-gcc"
      platform: x64
      compiler: gcc
    secrets: inherit

  build_linux_arm64_clang:
    name: "🐧 Linux ARM64 (Clang)"
    uses: ./.github/workflows/linux_build.yml
    with:
      jobName: "Linux ARM64 Clang Build"
      artifactPrefixName: "myMCpp-linux-arm64-clang"
      os: ubuntu-24.04-arm
      platform: arm64
      compiler: clang
    secrets: inherit

  build_linux_arm64_gcc:
    name: "🐧 Linux ARM64 (GCC)"
    uses: ./.github/workflows/linux_build.yml
    with:
      jobName: "Linux ARM64 GCC Build"
      artifactPrefixName: "myMCpp-linux-arm64-gcc"
      os: ubuntu-24.04-arm
      platform: arm64
      compiler: gcc
    secrets: inherit

  build_macos:
    name: "🍎 macOS"
    uses: ./.github/workflows/macos_build.yml
    with:
      jobName: "macOS Universal Build"
      artifactPrefixName: "myMCpp-macos-universal"
    secrets: inherit

  build_windows_x64_clang:
    name: "🪟 Windows x64 (Clang)"
    uses: ./.github/workflows/windows_build.yml
    with:
      jobName: "Windows x64 Clang Build"
      artifactPrefixName: "myMCpp-windows-x64-clang"
      platform: x64
      compiler: clang
    secrets: inherit

  build_windows_x64_msvc:
    name: "🪟 Windows x64 (MSVC)"
    uses: ./.github/workflows/windows_build.yml
    with:
      jobName: "Windows x64 MSVC Build"
      artifactPrefixName: "myMCpp-windows-x64-msvc"
      platform: x64
      compiler: msvc
    secrets: inherit

  build_windows_arm64_clang:
    name: "🪟 Windows ARM64 (Clang)"
    uses: ./.github/workflows/windows_build.yml
    with:
      jobName: "Windows ARM64 Clang Build"
      artifactPrefixName: "myMCpp-windows-arm64-clang"
      os: windows-11-arm
      platform: ARM64
      compiler: clang
    secrets: inherit

  build_windows_arm64_msvc:
    name: "🪟 Windows ARM64 (MSVC)"
    uses: ./.github/workflows/windows_build.yml
    with:
      jobName: "Windows ARM64 MSVC Build"
      artifactPrefixName: "myMCpp-windows-arm64-msvc"
      os: windows-11-arm
      platform: ARM64
      compiler: msvc
    secrets: inherit
