# Inspired by: https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/macos_build.yml

name: macOS Build Steps

on:
  workflow_call:
    inputs:
      jobName:
        required: true
        type: string
      artifactPrefixName:
        required: true
        type: string
      os:
        required: false
        type: string
        default: macos-latest
      buildType:
        required: false
        type: string
        default: Release
      cmakeFlags:
        required: false
        type: string
        default: ""
      fetchTags:
        required: false
        type: boolean
        default: false

jobs:
  build_macos:
    name: ${{ inputs.jobName }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    env:
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 9
      CCACHE_MAXSIZE: 100M

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      # actions/checkout elides tags, fetch them primarily for releases
      - name: Fetch Tags
        if: ${{ inputs.fetchTags }}
        run: git fetch --tags --no-recurse-submodules

      - name: Prepare Artifact Metadata
        id: artifact-metadata
        shell: bash
        env:
          PREFIX: ${{ inputs.artifactPrefixName }}
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          ARTIFACT_NAME="${PREFIX}"
          if [ "$EVENT_NAME" == "pull_request" ]; then
            PR_SHA_SHORT="${PR_SHA:0:8}"
            ARTIFACT_NAME="${PREFIX}-pr${PR_NUM}-${PR_SHA_SHORT}"
          fi
          echo "artifact-name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

      # -- SETUP CCACHE - https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: echo "timestamp=$(date -u "+%Y-%m-%d-%H;%M;%S")" >> $GITHUB_OUTPUT

      - name: Cache ccache
        uses: actions/cache@v5.0.5
        with:
          path: .ccache
          key: ${{ inputs.os }} ccache ${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: ${{ inputs.os }} ccache

      - name: Install Packages
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_ANALYTICS: 1
        run: |
          brew install ccache ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: '6.11.0'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtimageformats'
          cache: true
          use-official: true

      - name: Configure CMake
        run: |
          if [ "${{ inputs.buildType }}" = "Debug" ]; then
            PRESET="macos-dbg"
          else
            PRESET="macos-rel"
          fi
          cmake --preset $PRESET \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ${{ inputs.cmakeFlags }}

      - name: Build
        run: |
          if [ "${{ inputs.buildType }}" = "Debug" ]; then
            PRESET="macos-dbg"
          else
            PRESET="macos-rel"
          fi
          ccache -p
          ccache -z
          cmake --build --preset $PRESET
          ccache -s

      - name: Prepare Build Artifacts
        run: |
          if [ "${{ inputs.buildType }}" = "Debug" ]; then
            PRESET="macos-dbg"
            CONF="Debug"
          else
            PRESET="macos-rel"
            CONF="MinSizeRel"
          fi
          mkdir -p ci-artifacts
          mv build/$PRESET/bin/$CONF/myMCpp.app ci-artifacts/

      - name: Zip Build Artifacts
        run: |
          cd ci-artifacts
          TAG="$(git tag --points-at HEAD)"
          if [ -z "$TAG" ]; then
            APPNAME="${{ steps.artifact-metadata.outputs.artifact-name }}"
          else
            APPNAME="myMCpp-$TAG"
          fi
          mv myMCpp.app "$APPNAME.app"
          tar --options xz:compression-level=9 -cvJf "${{ steps.artifact-metadata.outputs.artifact-name }}.tar.xz" "$APPNAME.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact-metadata.outputs.artifact-name }}
          path: ci-artifacts/*.tar.xz
          if-no-files-found: error
          retention-days: 30
