name: Windows Build Steps
# Inspired by: https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/windows_build_qt.yml

on:
  workflow_call:
    inputs:
      jobName:
        required: true
        type: string
      artifactPrefixName:
        required: true
        type: string
      os:
        required: false
        type: string
        default: windows-2025-vs2026
      platform:
        required: false
        type: string
        default: x64
      compiler:
        required: false
        type: string
        default: clang
      buildType:
        required: false
        type: string
        default: Release
      cmakeFlags:
        required: false
        type: string
        default: ""
      fetchTags:
        required: false
        type: boolean
        default: false

jobs:
  build_windows:
    name: ${{ inputs.jobName }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # actions/checkout elides tags, fetch them primarily for releases
      - name: Fetch Tags
        if: ${{ inputs.fetchTags }}
        run: git fetch --tags --no-recurse-submodules

      - name: Prepare Artifact Metadata
        id: artifact-metadata
        shell: bash
        env:
          PREFIX: ${{ inputs.artifactPrefixName }}
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          ARTIFACT_NAME="${PREFIX}"
          if [ "$EVENT_NAME" == "pull_request" ]; then
            PR_SHA_SHORT="${PR_SHA:0:8}"
            ARTIFACT_NAME="${PREFIX}-pr${PR_NUM}-${PR_SHA_SHORT}"
          fi
          echo "artifact-name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ inputs.platform == 'ARM64' && 'arm64' || inputs.platform }}

      - name: Install Qt (x64)
        if: inputs.platform == 'x64'
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: '6.11.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtimageformats'
          cache: true
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git'
          use-official: true

      - name: Install Qt (ARM64)
        if: inputs.platform == 'ARM64'
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: '6.11.0'
          host: 'windows_arm64'
          target: 'desktop'
          arch: 'win64_msvc2022_arm64'
          modules: 'qtimageformats'
          cache: true
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git'
          use-official: true

      - name: Configure CMake (MSVC)
        if: inputs.compiler == 'msvc'
        shell: cmd
        run: |
          set VS_VER=2022
          if exist "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" (
            for /f "usebackq tokens=*" %%i in (`call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version "[18, 19)" -latest -property installationPath`) do set "VS2026PATH=%%i"
            if defined VS2026PATH (
              set VS_VER=2026
            ) else (
              for /f "usebackq tokens=*" %%i in (`call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version "[17, 18)" -latest -property installationPath`) do set "VS2022PATH=%%i"
              if defined VS2022PATH set VS_VER=2022
            )
          )
          if "${{ inputs.buildType }}" == "Debug" (
            set PRESET=win-dbg-%VS_VER%
          ) else (
            set PRESET=win-rel-%VS_VER%
          )
          echo PRESET=%PRESET%>> %GITHUB_ENV%
          cmake --preset %PRESET% ^
            ${{ inputs.cmakeFlags }}

      - name: Configure CMake (Clang)
        if: inputs.compiler == 'clang'
        shell: cmd
        run: |
          if "${{ inputs.platform }}" == "ARM64" (
            set CLANG_FLAGS=-march=armv8-a
          ) else (
            set CLANG_FLAGS=
          )
          if "${{ inputs.buildType }}" == "Debug" (
            set PRESET=win-clang-dbg
          ) else (
            set PRESET=win-clang-rel
          )
          echo PRESET=%PRESET%>> %GITHUB_ENV%
          cmake --preset %PRESET% ^
            -DCMAKE_CXX_FLAGS="%CLANG_FLAGS%" ^
            ${{ inputs.cmakeFlags }}

      - name: Build (MSVC)
        if: inputs.compiler == 'msvc'
        shell: cmd
        run: cmake --build --preset %PRESET% --parallel

      - name: Build (Clang)
        if: inputs.compiler == 'clang'
        shell: cmd
        run: cmake --build --preset %PRESET%

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact-metadata.outputs.artifact-name }}
          path: |
            ./build/${{ env.PRESET }}/bin
            !./build/${{ env.PRESET }}/bin/**/*.pdb
            !./build/${{ env.PRESET }}/bin/**/*.lib
            !./build/${{ env.PRESET }}/bin/**/*.exp
            !./build/${{ env.PRESET }}/bin/**/*.ilk
          if-no-files-found: error
          retention-days: 30
          overwrite: true

      - name: Upload symbols
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact-metadata.outputs.artifact-name }}-symbols
          path: |
            ./build/${{ env.PRESET }}/bin/**/*.pdb
          if-no-files-found: ignore
          retention-days: 30
          overwrite: true
